"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$03#31$$90lt#=7c+9z_5_qjws4gk#c##t@x2ne-9h$khre%6%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'corsheaders',
    'rest_framework',
    'wellness.apps.WellnessConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

SIMPLEUI_HOME_TITLE = '心理支持平台后台'
SIMPLEUI_HOME_ICON = 'fa fa-heart'
SIMPLEUI_INDEX = '后台首页'
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_LOGO = False
SIMPLEUI_DEFAULT_THEME = 'layui.css'
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['账号与权限', '心理服务管理', '内容与数据管理'],
    'menus': [
        {
            'name': '账号与权限',
            'icon': 'fas fa-user-shield',
            'models': [
                {'name': '用户', 'icon': 'fas fa-user', 'url': 'auth/user/'},
                {'name': '用户组', 'icon': 'fas fa-users', 'url': 'auth/group/'},
                {'name': '账号角色', 'icon': 'fas fa-id-card', 'url': 'wellness/accountprofile/'},
                {'name': '学生档案', 'icon': 'fas fa-address-card', 'url': 'wellness/studentprofile/'},
            ],
        },
        {
            'name': '心理服务管理',
            'icon': 'fas fa-hand-holding-heart',
            'models': [
                {'name': '咨询师', 'icon': 'fas fa-user-md', 'url': 'wellness/counselor/'},
                {'name': '咨询预约', 'icon': 'fas fa-calendar-check', 'url': 'wellness/appointment/'},
                {'name': '情绪日记', 'icon': 'fas fa-smile', 'url': 'wellness/moodentry/'},
                {'name': '匿名树洞', 'icon': 'fas fa-comment-dots', 'url': 'wellness/treeholepost/'},
                {'name': '树洞回应', 'icon': 'fas fa-reply', 'url': 'wellness/treeholereply/'},
                {'name': '危机预警', 'icon': 'fas fa-exclamation-triangle', 'url': 'wellness/crisisalert/'},
            ],
        },
        {
            'name': '内容与数据管理',
            'icon': 'fas fa-chart-line',
            'models': [
                {'name': '心理科普文章', 'icon': 'fas fa-book-open', 'url': 'wellness/article/'},
                {'name': '外部资源源站', 'icon': 'fas fa-globe', 'url': 'wellness/externalresourcesource/'},
                {'name': '资源抓取记录', 'icon': 'fas fa-history', 'url': 'wellness/resourcefetchlog/'},
                {'name': '心理量表', 'icon': 'fas fa-clipboard-list', 'url': 'wellness/assessmentscale/'},
                {'name': '量表记录', 'icon': 'fas fa-poll', 'url': 'wellness/assessmentrecord/'},
            ],
        },
    ],
}
