# Generated by Django 5.2.15 on 2026-06-22 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('source', models.CharField(blank=True, max_length=120, verbose_name='来源')),
                ('category', models.CharField(max_length=40, verbose_name='分类')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('content', models.TextField(verbose_name='正文')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
            ],
            options={
                'verbose_name': '心理科普文章',
                'verbose_name_plural': '心理科普文章',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=80, verbose_name='量表名称')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='量表编码')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('questions', models.JSONField(default=list, verbose_name='题目')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='最高分')),
            ],
            options={
                'verbose_name': '心理量表',
                'verbose_name_plural': '心理量表',
            },
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=40, verbose_name='姓名')),
                ('title', models.CharField(max_length=80, verbose_name='职称')),
                ('specialties', models.JSONField(default=list, verbose_name='擅长领域')),
                ('qualifications', models.TextField(blank=True, verbose_name='资质说明')),
                ('available_slots', models.JSONField(default=list, verbose_name='可预约时段')),
                ('avatar_color', models.CharField(default='#d85d73', max_length=20, verbose_name='头像色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可预约')),
            ],
            options={
                'verbose_name': '咨询师',
                'verbose_name_plural': '咨询师',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student_no', models.CharField(max_length=32, unique=True, verbose_name='学号')),
                ('college', models.CharField(blank=True, max_length=80, verbose_name='学院')),
                ('grade', models.CharField(blank=True, max_length=30, verbose_name='年级')),
                ('privacy_consent', models.BooleanField(default=False, verbose_name='隐私授权')),
                ('pressure_sources', models.JSONField(blank=True, default=list, verbose_name='压力来源')),
                ('preferred_topics', models.JSONField(blank=True, default=list, verbose_name='偏好主题')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '学生档案',
                'verbose_name_plural': '学生档案',
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('mood', models.CharField(max_length=30, verbose_name='情绪')),
                ('intensity', models.PositiveSmallIntegerField(default=5, verbose_name='强度')),
                ('sleep_quality', models.PositiveSmallIntegerField(default=5, verbose_name='睡眠质量')),
                ('pressure_sources', models.JSONField(blank=True, default=list, verbose_name='压力来源')),
                ('note', models.TextField(blank=True, verbose_name='日记')),
                ('is_private', models.BooleanField(default=True, verbose_name='是否私密')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to='wellness.studentprofile', verbose_name='学生')),
            ],
            options={
                'verbose_name': '情绪日记',
                'verbose_name_plural': '情绪日记',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrisisAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('level', models.CharField(choices=[('notice', '关注'), ('warning', '预警'), ('critical', '危机')], default='notice', max_length=16, verbose_name='等级')),
                ('trigger', models.CharField(max_length=160, verbose_name='触发原因')),
                ('handled', models.BooleanField(default=False, verbose_name='是否处理')),
                ('handler_note', models.TextField(blank=True, verbose_name='处理记录')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crisis_alerts', to='wellness.studentprofile', verbose_name='学生')),
            ],
            options={
                'verbose_name': '危机预警',
                'verbose_name_plural': '危机预警',
                'ordering': ['handled', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('score', models.PositiveIntegerField(verbose_name='得分')),
                ('risk_level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='low', max_length=12, verbose_name='风险等级')),
                ('answers', models.JSONField(blank=True, default=list, verbose_name='答题记录')),
                ('suggestion', models.TextField(blank=True, verbose_name='建议')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='wellness.assessmentscale', verbose_name='量表')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_records', to='wellness.studentprofile', verbose_name='学生')),
            ],
            options={
                'verbose_name': '量表记录',
                'verbose_name_plural': '量表记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('scheduled_at', models.DateTimeField(verbose_name='预约时间')),
                ('topic', models.CharField(max_length=120, verbose_name='咨询主题')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('finished', '已完成'), ('cancelled', '已取消')], default='pending', max_length=16, verbose_name='状态')),
                ('confidential_note', models.TextField(blank=True, verbose_name='保密备注')),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='wellness.counselor', verbose_name='咨询师')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='wellness.studentprofile', verbose_name='学生')),
            ],
            options={
                'verbose_name': '咨询预约',
                'verbose_name_plural': '咨询预约',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
