# Generated by Django 5.2.15 on 2026-06-22 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeHolePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.CharField(choices=[('study', '学业压力'), ('relationship', '人际关系'), ('family', '家庭关系'), ('growth', '自我成长'), ('other', '其他')], default='other', max_length=24, verbose_name='分类')),
                ('content', models.TextField(verbose_name='倾诉内容')),
                ('mood_tag', models.CharField(blank=True, max_length=30, verbose_name='情绪标签')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='是否匿名')),
                ('support_count', models.PositiveIntegerField(default=0, verbose_name='支持数')),
                ('risk_flag', models.BooleanField(default=False, verbose_name='风险标记')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treehole_posts', to='wellness.studentprofile', verbose_name='学生')),
            ],
            options={
                'verbose_name': '匿名树洞',
                'verbose_name_plural': '匿名树洞',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreeHoleReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('responder_name', models.CharField(default='同伴支持者', max_length=40, verbose_name='回应者')),
                ('content', models.TextField(verbose_name='回应内容')),
                ('is_counselor_reply', models.BooleanField(default=False, verbose_name='咨询师回应')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='wellness.treeholepost', verbose_name='树洞')),
            ],
            options={
                'verbose_name': '树洞回应',
                'verbose_name_plural': '树洞回应',
                'ordering': ['created_at'],
            },
        ),
    ]
