# Generated by Django 5.2.15 on 2026-06-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0008_studentprofile_student_no_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True, verbose_name='配置编号')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用 AI 倾听')),
                ('provider', models.CharField(choices=[('auto', '自动检测'), ('openai', 'OpenAI'), ('deepseek', 'DeepSeek'), ('custom', '自定义兼容接口')], default='auto', max_length=20, verbose_name='服务商')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key')),
                ('api_url', models.URLField(default='https://api.openai.com/v1/chat/completions', verbose_name='API 地址')),
                ('model', models.CharField(blank=True, max_length=80, verbose_name='模型')),
                ('auto_detect_model', models.BooleanField(default=True, verbose_name='自动检测并选择模型')),
                ('timeout', models.PositiveSmallIntegerField(default=30, verbose_name='超时秒数')),
            ],
            options={
                'verbose_name': 'AI 倾听配置',
                'verbose_name_plural': 'AI 倾听配置',
            },
        ),
    ]
